# Объявления
@hostname = http://localhost
@port = 7777
@host = {{hostname}}:{{port}}
@parentPath = offers
@contentType = application/json
@offerId = 647f0adebc49a7eb82cd23c3
@cityId = 647f0adebc49a7eb82cd23c1
@userId = 6490546840fa3a8fda6141ad
@token = eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InRvcmFuczg4OEBvdmVybG9vay5uZXQiLCJpZCI6IjY0OTA1YTI0YTNlNzk0NDQ2ZDgxZWZlZCIsImlhdCI6MTY4NzE4MTg4MCwiZXhwIjoxNjg3MzU0NjgwfQ.Se5XEQpZD2cdEtnSApt9QA9oXPlYdOqwHaAq39TJIwI

## Список объявлений
GET {{host}}/{{parentPath}} HTTP/1.1
###
## Список объявлений для авторизованных
GET {{host}}/{{parentPath}} HTTP/1.1
Authorization: Bearer {{token}}
###

## Список только избранных объявлений для авторизованных
GET {{host}}/{{parentPath}}/favorites HTTP/1.1
Authorization: Bearer {{token}}
###
## Список объявлений с лимитом
GET {{host}}/{{parentPath}}?limit=2 HTTP/1.1
###
## Список объявлений с сортировкой
# Default | Rated | Popular | PriceTop | PriceDown
GET {{host}}/{{parentPath}}?sortType=PriceTop HTTP/1.1
###
## Список объявлений определённого города
GET {{host}}/{{parentPath}}/city/{{cityId}}?limit=10 HTTP/1.1
###
## Список премиум объявлений
GET {{host}}/{{parentPath}}/premium/city/{{cityId}}?sortType=Popular HTTP/1.1
###

## Объявление по идентификатору
GET {{host}}/{{parentPath}}/{{offerId}} HTTP/1.1
###
## Создание объявления
POST {{host}}/{{parentPath}} HTTP/1.1
Content-Type: {{contentType}}
Authorization: Bearer {{token}}

{
  "title": "Премиум title",
  "description": "Новый детективный роман от короля ужасов.",
  "preview": "billy-summers.png",
  "images": ["img1.png","img2.png"],
  "type": "Apartment",
  "price": 777,
  "guests": 10,
  "rooms": 1,
  "rating":0,
  "commentsCount": 0,
  "features": ["Breakfast"],
  "city": "Dusseldorf",
  "author": "{{userId}}",
  "isPremium": true,
  "coordinates":{
    "latitude": 50,
    "longitude": 0
  }
}
###  "sgsgsg": 111,
###  "10": 10
###
## Удаление объявления

DELETE {{host}}/{{parentPath}}/{{offerId}}  HTTP/1.1
Authorization: Bearer {{token}}

###
## Обновление объявления

PATCH {{host}}/{{parentPath}}/{{offerId}} HTTP/1.1
Content-Type: {{contentType}}
Authorization: Bearer {{token}}

{
  "title": "Премиум title new",
  "features": ["Breakfast"],
  "description": "Проверка обновления 1111111",
  "commentsCount": 0
}

###
## Отправка preview объявления

POST {{host}}/{{parentPath}}/{{offerId}}/preview HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="offer-preview"; filename="preview.jpg"
Content-Type: image/jpeg

< /Users/dmitrij/Documents/preview.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###
## Отправка images объявления
POST {{host}}/{{parentPath}}/{{offerId}}/images HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="offer-img"; filename="preview1.jpg"
Content-Type: image/jpeg

< /Users/dmitrij/Documents/preview1.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="offer-img"; filename="preview2.jpg"
Content-Type: image/jpeg

< /Users/dmitrij/Documents/preview2.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###
## Отправка архива вместо изображения

POST {{host}}/{{parentPath}}/{{offerId}}/preview HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="offer-preview"; filename="preview.jpg"
Content-Type: application/zip

< /Users/dmitrij/Documents/test.zip
------WebKitFormBoundary7MA4YWxkTrZu0gW--
