# Объявления
@hostname = http://localhost
@port = 7777
@host = {{hostname}}:{{port}}
@parentPath = offers
@contentType = application/json
@offerId = 64985983b6459fb14222a82f
@cityId = 647f0adebc49a7eb82cd23c1
@token =eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6IjFAMS5ydSIsImlkIjoiNjQ5ZThiYzc5OWU1ZGI3YjVhNmY2ZmI0IiwiaWF0IjoxNjg4MTEyMzgwLCJleHAiOjE2ODgyODUxODB9.UVljwkuuG2Jk3HZWD6Puz2FULSifhyrat63GPH4JtDc

## Список объявлений
GET {{host}}/{{parentPath}} HTTP/1.1
###
## Список объявлений для авторизованных
GET {{host}}/{{parentPath}} HTTP/1.1
Authorization: Bearer {{token}}
###

## Список только избранных объявлений для авторизованных
GET {{host}}/{{parentPath}}/favorites HTTP/1.1
Authorization: Bearer {{token}}
###
## Список объявлений с лимитом
GET {{host}}/{{parentPath}}?limit=2 HTTP/1.1
###
## Список объявлений с сортировкой
# Default | Rated | Popular | PriceTop | PriceDown
GET {{host}}/{{parentPath}}?sortType=PriceTop HTTP/1.1
###
## Список объявлений определённого города
GET {{host}}/{{parentPath}}/city/{{cityId}}?limit=10 HTTP/1.1
###
## Список премиум объявлений
GET {{host}}/{{parentPath}}/premium/city/{{cityId}}?sortType=Popular HTTP/1.1
###

## Объявление по идентификатору
GET {{host}}/{{parentPath}}/{{offerId}} HTTP/1.1
###
## Создание объявления
POST {{host}}/{{parentPath}} HTTP/1.1
Content-Type: {{contentType}}
Authorization: Bearer {{token}}

{
  "title": "New Cologne best",
  "description": "Новый детективный роман от короля ужасов.",
  "type": "House",
  "price": 999,
  "guests": 1,
  "rooms": 1,
  "rating":0,
  "commentsCount": 0,
  "features": ["Breakfast", "Workspace"],
  "city": "Cologne",
  "isPremium": true,
  "coordinates":{
    "latitude": 50,
    "longitude": 0
  }
}
###
## Удаление объявления

DELETE {{host}}/{{parentPath}}/{{offerId}}  HTTP/1.1
Authorization: Bearer {{token}}

###
## Обновление объявления

PATCH {{host}}/{{parentPath}}/{{offerId}} HTTP/1.1
Content-Type: {{contentType}}
Authorization: Bearer {{token}}

{
  "title": "Премиум title new",
  "features": ["Breakfast"],
  "description": "Проверка обновления",
  "commentsCount": 0
}

###
## Отправка preview объявления

POST {{host}}/{{parentPath}}/{{offerId}}/preview HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="offer-preview"; filename="preview.jpg"
Content-Type: image/jpeg

< /Users/dmitrij/Documents/preview.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###
## Отправка images объявления
POST {{host}}/{{parentPath}}/{{offerId}}/images HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="offer-img"; filename="preview1.jpg"
Content-Type: image/jpeg

< /Users/dmitrij/Documents/preview1.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="offer-img"; filename="preview2.jpg"
Content-Type: image/jpeg

< /Users/dmitrij/Documents/preview2.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="offer-img"; filename="preview3.jpg"
Content-Type: image/jpeg

< /Users/dmitrij/Documents/preview3.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="offer-img"; filename="preview4.jpg"
Content-Type: image/jpeg

< /Users/dmitrij/Documents/preview4.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="offer-img"; filename="preview5.jpg"
Content-Type: image/jpeg

< /Users/dmitrij/Documents/preview5.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="offer-img"; filename="preview6.jpg"
Content-Type: image/jpeg

< /Users/dmitrij/Documents/preview6.jpg
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###
## Отправка архива вместо изображения

POST {{host}}/{{parentPath}}/{{offerId}}/preview HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="offer-preview"; filename="preview.jpg"
Content-Type: application/zip

< /Users/dmitrij/Documents/test.zip
------WebKitFormBoundary7MA4YWxkTrZu0gW--
