# Комментарии
@hostname = http://localhost
@port = 7777
@host = {{hostname}}:{{port}}
@parentPath = comments
@contentType = application/json
@offerId = 64878247de892784994580e0
@cityId = 647cf5d2f10888c3cba79042
@userId = 647cf5d2f10888c3cba7903f

## Список комментариев
GET {{host}}/{{parentPath}} HTTP/1.1
###

## Комменты по идентификатору объявления
GET {{host}}/{{parentPath}}/{{offerId}} HTTP/1.1
###

## Создание комментария

POST {{host}}/{{parentPath}} HTTP/1.1
Content-Type: {{contentType}}

{
  "text": "Всё супер!",
  "offerId":"{{offerId}}",
  "userId": "{{userId}}",
  "rating": 5
}
###
