# Комментарии
@hostname = http://localhost
@port = 7777
@host = {{hostname}}:{{port}}
@parentPath = comments
@contentType = application/json
@offerId = 648af246c61bce18b74bdc47
@cityId = 647cf5d2f10888c3cba79042
@userId = 647cf5d2f10888c3cba7903f
@token = eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InRvcmFuczc3N0BvdmVybG9vay5uZXQiLCJpZCI6IjY0OGIzNjFjYzI4MmEyOTU5NTliYmM5MCIsImlhdCI6MTY4Njg0NzgzMiwiZXhwIjoxNjg3MDIwNjMyfQ.jn_DoD5F9sZizHHFaQlNBy25Kb103CopW-vwanzcBzk

## Комменты по идентификатору объявления
GET {{host}}/{{parentPath}}/{{offerId}} HTTP/1.1
###

## Создание комментария
POST {{host}}/{{parentPath}}/{{offerId}} HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: {{contentType}}

{
  "text": "Всё no супер!",
  "rating": 1
}
###
