# Города
@hostname = http://localhost
@port = 7777
@host = {{hostname}}:{{port}}
@parentPath = cities
@cityId = 647cf5d2f10888c3cba79052
@contentType = application/json



### Получить список городов
GET {{host}}/{{parentPath}} HTTP/1.1
### 
## Список объявления определённого города

GET {{host}}/{{parentPath}}/{{cityId}}/offers?limit=10 HTTP/1.1

###
