# Пользователь
@hostname = http://localhost
@port = 7777
@host = {{hostname}}:{{port}}
@parentPath = users
@contentType = application/json



### Регистрация пользователя
POST {{host}}/{{parentPath}}/register HTTP/1.1
Content-Type: {{contentType}}

{
  "email": "torans1@overlook.net",
  "avatarPath": "torrance.png",
  "firstName": "Jack",
  "password": "shining"
}