# Пользователь
@hostname = http://localhost
@port = 7777
@host = {{hostname}}:{{port}}
@parentPath = users
@contentType = application/json
@offerId= 649ae0c5659feceaf79e1280

@token =eyJhbGciOiJIUzI1NiJ9.eyJlbWFpbCI6InRvcmFuczEwQG92ZXJsb29rLm5ldCIsImlkIjoiNjQ5YWUwN2Q2NTlmZWNlYWY3OWUxMjY4IiwiaWF0IjoxNjg3ODcyOTk5LCJleHAiOjE2ODgwNDU3OTl9.DdqkJl2YHE5UFP5atMWci_VYEKLLAVCOAxE5HhpRrYo

### Регистрация пользователя
POST {{host}}/{{parentPath}}/register HTTP/1.1
Content-Type: {{contentType}}

{
  "email": "torans10@overlook.net",
  "firstName": "Jack",
  "password": "shining",
  "type": "default"
}

###

## Авторизовать пользователя

POST {{host}}/{{parentPath}}/login HTTP/1.1
Content-Type: {{contentType}}

{
  "email": "torans10@overlook.net",
  "password": "shining"
}

###
## Проверка авторизации

GET {{host}}/{{parentPath}}/login HTTP/1.1
Authorization: Bearer {{token}}
###


### Список избранного
GET {{host}}/{{parentPath}}/favorites HTTP/1.1
Authorization: Bearer {{token}}
###
### Добавить в избранное
POST {{host}}/{{parentPath}}/favorites/add/{{offerId}} HTTP/1.1
Authorization: Bearer {{token}}
###
### Удалить из избранного
DELETE  {{host}}/{{parentPath}}/favorites/remove/{{offerId}} HTTP/1.1
Authorization: Bearer {{token}}
###

###
## Отправка аватарки пользователю

POST {{host}}/{{parentPath}}/avatar HTTP/1.1
Authorization: Bearer {{token}}
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="avatar"; filename="man.png"
Content-Type: image/png

< /Users/dmitrij/Documents/man.png
------WebKitFormBoundary7MA4YWxkTrZu0gW--
